pages:
  image: node:17.4.0
  stage: build
  script:
    - yarn
    - yarn build
    - mv public public_files
    - mv build public
    - cd parser
    - yarn
    - yarn build
    - mv build ../public/parser
  artifacts:
    expire_in: 1 week
    paths:
      - public
  cache:
    paths:
    - node_modules
    - parser/node_modules


